### ISSUE TITLE
When retrieving users, only include direct group memberships in the user info

### ISSUE THREAD

**Issue by lesavage** [adobe-apiplatform/umapi-client.py#44]
When calling either of the following UM APIs ensure that the directOnly query parameter is set to true:

/users/{orgId}/{page}
/users/{orgId}/{page}/{groupName}

**Comment by adobeDan** [comment]
Thanks for the bug report.  This is to prevent retrieved users from appearing to be both in user groups and the product configurations containing those user groups.  I'm adding it as a default parameter to the UsersQuery action.

**Comment by adobeDan** [comment]
This now makes the results of UsersQuery exactly match the group mappings projected on directory users, with no spurious product configurations.
