### ISSUE TITLE
Adding Proxy Authentication Support

### ISSUE THREAD

**Issue by bhunut-adobe** [adobe-apiplatform/umapi-client.py#52]
A customer request UST and UMAPI to have Proxy and Proxy Authentication support on the application level.

**Comment by adobeDan** [comment]
We use the OS network stacks, all of which (to my knowledge) provide both proxy and proxy-authentication capabilities.  I'm marking this wontfix and will close it in a week unless someone shows me an OS we run on that has no authenticated-proxy support.
