### ISSUE TITLE
Role assignment doesn't work

### ISSUE THREAD

**Issue by adorton-adobe** [adobe-apiplatform/umapi-client.py#64]
According to the [UMAPI docs](https://adobe-apiplatform.github.io/umapi-documentation/en/api/ActionsCmds.html#addRemoveAttr), we should be able to assign admin roles using the UMAPI's existing group assignment.  

It currently doesn't work with the umapi-client.  I still need to confirm, but I believe this is due to the fact that the umapi-client still uses "product" and "userGroup" as keys when adding groups to a user.  According to [the docs](https://adobe-apiplatform.github.io/umapi-documentation/en/api/ActionsCmds.html#addRemoveAttr), the valid key is just "group" (for roles, product profiles, and user groups).

**Comment by phil-levy** [comment]
The old spellings of the "group" term should still be accepted.  In case they aren't, an error should be returned.

**Comment by adorton-adobe** [comment]
They appear to be accepted for normal group or profile assignment, but not admin roles.  I don't think the UMAPI returns an error.  I'll test to confirm.

**Comment by adorton-adobe** [comment]
Perhaps the bug is in the UMAPI itself and not the client.  Still, we should update the client to use "group" since that is what the documentation now specifies.

**Comment by Luci2015** [comment]
You cannot add system admins (at least yet), if that's what you tried to do. The UMAPI has the option but the call would be a fail.
You could create a support type of admin, via the UM API directly -> worked in my case

**Comment by adorton-adobe** [comment]
Closing because I can't reproduce this
