### ISSUE TITLE
managing [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by Luci2015** [adobe-apiplatform/umapi-client.py#70]
Avoiding this error one could use the REQUESTS_CA_BUNDLE environment variable to point to the proxy's root CA cert, but could be useful to have it incorporated in the script, so that the 'verify' argument from requests be used and the value to pass be picked up from a config file.
Raising this here as the user_sync uses the Connection module from here.

**Comment by adorton-adobe** [comment]
This has been released in 2.14.
