### ISSUE TITLE
Federated ID creation fails with invalidKey when specifying anything other than email

### ISSUE THREAD

**Issue by chuckknucka** [adobe-apiplatform/umapi-client.py#77]
When performing a create user action...

```
user_action = umapi_client.UserAction(email='email@email.com', id_type='federatedID', first_name="Bob", last_name="Smith", country="US")
user_action.create()
```
The umapi_client module builds a command list and a frame.
```
user_action.commands
# [{'createFederatedID': {'email': 'email@email.com', 'option': 'ignoreIfAlreadyExists'}}]

user_action.frame
# {'country': 'US', 'first_name': 'Bob', 'last_name': 'Smith', 'user': 'email@email.com'}
```

Frame values show up in a 'target' attribute sent to the UMAPI.  It appears that the UMAPI doesn't appreciate those values appearing in the 'target' attribute rather than in the command as it responds with 'Illegal JSON command entry: invalidKey'

The API documentation seems to confirm that these values should appear in the command.
https://adobe-apiplatform.github.io/umapi-documentation/en/api/ActionsCmds.html#createFederatedID

When those attributes are manually removed from `user_action.frame` and put into `user_action[0]['createFederatedID']`, the command succeeds.

What the umapi_client builds:
```
user_action.execution_errors()
[{'command': {'createFederatedID': {'email': u'redacted@email.com',
     'option': 'ignoreIfAlreadyExists'}},
   u'errorCode': u'error.command.malformed',
   u'message': u'Illegal JSON command entry: invalidKey',
   'target': {'country': 'US',
    'first_name': u'Redacted',
    'last_name': u'Jones',
    'user': u'redacted@email.com'}}]
```

When manually corrected:
```
user_action[0]['createFederatedID'].update({
   'firstname': "Redacted",
   'lastname': "Jones",
   'country': "US"
})
del user_action.frame['firstname']
del user_action.frame['lastname']
del user_action.frame['country']

result = conn.execute_single(user_action. immediate=True)
result
# (0, 1, 1)
```

This issue can be worked around by not specifying country, firstname or lastname.  I also tried with first_name and last_name attributes that include underscores but it doesn't seem to matter.  I haven't tested a subsequent update operation to populate those values.

**Comment by adorton-adobe** [comment]
When constructing a `UserAction` object, you only need to supply the top-level action attributes e.g. the identity type, `user`, `domain` (if applicable) and `requestID` (if desired).

The new user's attributes e.g. `firstname`, `lastname`, `email`, `country` and `option` are supplied to the `create()` call. (since those are attributes of the `createFederatedID` directive in the underlying JSON object)

```python
user = umapi_client.UserAction('federatedID', email, username, domain)
user.create(firstname, lastname, country, email)
```

**Comment by chuckknucka** [comment]
OK, I will try that and report back.  Thanks.

**Comment by chuckknucka** [comment]
OK, that worked.  Not sure where I got the idea to push those extra attributes into the UserAction constructor, but I appreciate the assist.
