### ISSUE TITLE
UserGroupsQuery(conn).all_results() raises ValueError on 404

### ISSUE THREAD

**Issue by necabo** [adobe-apiplatform/umapi-client.py#82]
Looking at the code it seems like with recent changes to [query_multiple()](https://github.com/adobe-apiplatform/umapi-client.py/blob/v2.15/umapi_client/connection.py#L278) in the v2.15 release, the [code path for 404](https://github.com/adobe-apiplatform/umapi-client.py/blob/v2.15/umapi_client/connection.py#L311) was forgotten. 

The different number of return values eventually leads to a `ValueError` when trying to evaluate the lazy query. That occurs in [_next_page()](https://github.com/adobe-apiplatform/umapi-client.py/blob/v2.15/umapi_client/api.py#L212) because it's attempting to unpack 6 values when only 2 are returned.

**Comment by adorton-adobe** [comment]
This should be fixed in #92. Let me know if you still have issues.
